import type { Metadata } from 'next';

import './globals.css';
import Alert from '@/components/Alert';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className='relative flex size-full'>
        <Alert />
        {children}
      </body>
    </html>
  );
}
